version: "3.11"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
    command: >
      sh -c "uvicorn --host 0.0.0.0 --port 8000 app.api.main:app"
